### ISSUE TITLE
Only register commands you have ENVARs for 

### ISSUE THREAD

**Issue by ntindle** [isaiahbjork/Auto-GPT-Crypto-Plugin#2]
Right now, your plugin can crash autogpt if you don't have the envars set correctly and it tries to execute one of your commands that were registered. Only allow registering of a command once the relevant keys are added

https://github.com/isaiahbjork/Auto-GPT-Crypto-Plugin/blob/c6a130dd698359e7cc10e1aa3f8116f06434dd43/src/auto_gpt_crypto/__init__.py#L49

**Comment by isaiahbjork** [comment]
Everything should be fixed now.
